### ISSUE TITLE
Export to .csv file

### ISSUE THREAD

**Issue by burnNturn** [burnNturn/edenvr-survey#6]
Would like to be able to export the data (preferably filtered data) to a CSV file.

**Comment by Jabronious** [comment]
When doing this we will want to use http://sidekiq.org/ because as the data gets larger it can hold up the server trying to process the export.

**Comment by burnNturn** [comment]
I finally figured out how to do the exporting (without sidekiq) the filtered results.  The exporting #@customers.all was easy, but using the filtered results was time consuming.  

I don't think that it will end up getting big enough to need sidekiq, but I can see the need for sidekiq in other task (for this project, and another project I have in mind) so I'll probably work on implementing it.  Might not end up using it though for this task because I would prefer a direct download, not having to get a link (like will need to be done with sidekiq from what I see).

**Comment by Jabronious** [comment]
@burnNturn should this be closed?
