### ISSUE TITLE
Add error message when a field is not filled out on the customer#create form

### ISSUE THREAD

**Issue by Jabronious** [burnNturn/edenvr-survey#7]
Currently when you submit a form without filling out the information it does not inform you anything was incorrect.

**Comment by burnNturn** [comment]
Tried a couple of things, both in _form.html.erb and customer controller.  Only tried making changes on the game field.  Couldn't get either to work, from what I read, this seems to be the way to do it.  I can see that I am getting a validation error when it tries to push it to the database, but can't get it to display an error message.  Shouldn't the code at the top off my _form.html.erb be at least displaying an overall error message for the whole form?

**Comment by burnNturn** [comment]
Pulled and merged #10 to add client side validation.
